export const ANIMATION = {
  STAGGER_DELAY: 150,
  HERO_SUBTITLE_DELAY: 500,
  HERO_DESCRIPTION_DELAY: 700,
  FADE_DURATION: 700,
  TRANSITION_DURATION: 300,
  NAV_SCROLL_THRESHOLD: 100,
} as const;

export const INTERSECTION = {
  THRESHOLD: 0.1,
  ROOT_MARGIN: '0px 0px -50px 0px',
} as const;

export const LAYOUT = {
  SECTION_SCROLL_MARGIN: '5rem',
  PRESS_IMAGE_HEIGHT: 'h-56',
  HERO_IMAGE_MAX_WIDTH_MOBILE: 'max-w-[220px]',
  HERO_IMAGE_MAX_WIDTH_DESKTOP: 'lg:max-w-[280px]',
} as const;
